kind: Pod
apiVersion: v1
metadata:
  name: {{.JobName}}-{{.Iteration}}
  labels:
    name: {{.JobName}}
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
spec:
  nodeSelector: {{.nodeSelector}}
  securityContext:
    runAsNonRoot: true
  containers:
  - name: node-density
    image: {{.containerImage}}
    resources:
      requests:
        memory: "10Mi"
        cpu: "10m"
    ports:
    - containerPort: 8080
      protocol: TCP
    imagePullPolicy: IfNotPresent


